- 데이터셋 명 / 데이터수 / label 수

In [28]:
import pandas as pd
data = pd.read_excel("/home/SANGHEE/roa-text-classification/datasets/original/invest.xlsx", index_col=0)

In [29]:
data

,title,text,label
28595,재외국민 지원. 안녕하세요 저희는 일본에서 살고있는 학생입니다 일본에서 태어나거나 ...,재외국민 지원. 안녕하세요 저희는 일본에서 살고있는 학생입니다 일본에서 태어나거나 ...,1
7691,대구 계명대 정은희살인사체유기 사체손괴 유전자 조작교사 사건. 청원시작\n청원진행중...,대구 계명대 정은희살인사체유기 사체손괴 유전자 조작교사 사건. 청원시작\n청원진행중...,0
4408,데이터폭력. 데이트폭력으로 많은 여성들이 다치고 목숨을 잃는것을보고\n법을 강력하게...,데이터폭력. 데이트폭력으로 많은 여성들이 다치고 목숨을 잃는것을보고\n법을 강력하게...,0
26316,"세계적인 거장 데니스 오펜하임""꽃의 내부"" 진짜는 어디에 있는가?. <해운대구, 세...","세계적인 거장 데니스 오펜하임""꽃의 내부"" 진짜는 어디에 있는가?. <해운대구, 세...",1
32755,국가 무형문화재 제15호 북청사자놀음보존회 정상화를위한 적폐청산. 사)국가 무형문화...,국가 무형문화재 제15호 북청사자놀음보존회 정상화를위한 적폐청산. 사)국가 무형문화...,1
...,...,...,...
23796,타투리스트가 되기 위해 의료적 과정을 거치지 않고 따로 타투리스트라는 직업을 인정하...,타투리스트가 되기 위해 의료적 과정을 거치지 않고 따로 타투리스트라는 직업을 인정하...,1
15393,'미투' 거짓 제보자를 처벌해주세요.. 최근 '미투'가 시작되면서 자신이 성범죄 피...,'미투' 거짓 제보자를 처벌해주세요.. 최근 '미투'가 시작되면서 자신이 성범죄 피...,0
15820,"손흥민 아시안컵 4강부터 출전시켜라. 소속팀에 기여 및 체력안배, 부상방지를 ...","손흥민 아시안컵 4강부터 출전시켜라. 소속팀에 기여 및 체력안배, 부상방지를 ...",1
2172,정치적 행보를 신성한 스포츠와 엮는 행동을 하지마세요. 왜 국가는 정치를 신성한 ...,정치적 행보를 신성한 스포츠와 엮는 행동을 하지마세요. 왜 국가는 정치를 신성한 ...,1
6892,정부는 국민의 목소리를 들어주세요.. 이정도면 무시라고 봐도 무방할 정도의 현실입니...,정부는 국민의 목소리를 들어주세요.. 이정도면 무시라고 봐도 무방할 정도의 현실입니...,0

In [30]:
def preprocessing(title, text) : 
    return "[제목] " + title + " [본문]" + text

In [31]:
data["data"] = data[["title", "text"]].apply(lambda x : preprocessing(x["title"], x["text"]), axis=1)
data = data[["data", "label"]]

In [32]:
data = data[["data", "label"]]

In [33]:
data

                                                    data  label
28595  [제목] 재외국민 지원. 안녕하세요 저희는 일본에서 살고있는 학생입니다 일본에서 태...      1
7691   [제목] 대구 계명대 정은희살인사체유기 사체손괴 유전자 조작교사 사건. 청원시작\n...      0
4408   [제목] 데이터폭력. 데이트폭력으로 많은 여성들이 다치고 목숨을 잃는것을보고\n법을...      0
26316  [제목] 세계적인 거장 데니스 오펜하임"꽃의 내부" 진짜는 어디에 있는가?. <해운...      1
32755  [제목] 국가 무형문화재 제15호 북청사자놀음보존회 정상화를위한 적폐청산. 사)국가...      1
...                                                  ...    ...
23796  [제목] 타투리스트가 되기 위해 의료적 과정을 거치지 않고 따로 타투리스트라는 직업...      1
15393  [제목] '미투' 거짓 제보자를 처벌해주세요.. 최근 '미투'가 시작되면서 자신이 ...      0
15820  [제목] 손흥민  아시안컵 4강부터  출전시켜라. 소속팀에 기여  및 체력안배, 부...      1
2172   [제목] 정치적 행보를  신성한 스포츠와 엮는 행동을 하지마세요. 왜 국가는 정치를...      1
6892   [제목] 정부는 국민의 목소리를 들어주세요.. 이정도면 무시라고 봐도 무방할 정도의...      0

[3000 rows x 2 columns]